steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    secretEnv: [
        "ACCESS_TOKEN_KEY",
        "MYSQLHOST",
        "MYSQLPASSWORD",
        "MYSQLUSER",
        "REFRESH_TOKEN_KEY",
      ]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo $'\n  ACCESS_TOKEN_KEY: '$$ACCESS_TOKEN_KEY >> app.yaml
        echo $'\n  MYSQLHOST: '$$MYSQLHOST >> app.yaml
        echo $'\n  MYSQLPASSWORD: '$$MYSQLPASSWORD >> app.yaml
        echo $'\n  MYSQLUSER: '$$MYSQLUSER >> app.yaml
        echo $'\n  REFRESH_TOKEN_KEY: '$$REFRESH_TOKEN_KEY >> app.yaml
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy
        gcloud app browse
timeout: "1600s"
availableSecrets:
  secretManager:
    - versionName: projects/673277218150/secrets/ACCESS_TOKEN_KEY/versions/1
      env: "ACCESS_TOKEN_KEY"
    - versionName: projects/673277218150/secrets/MYSQLHOST/versions/1
      env: "MYSQLHOST"
    - versionName: projects/673277218150/secrets/MYSQLPASSWORD/versions/1
      env: "MYSQLPASSWORD"
    - versionName: projects/673277218150/secrets/MYSQLUSER/versions/1
      env: "MYSQLUSER"
    - versionName: projects/673277218150/secrets/REFRESH_TOKEN_KEY/versions/1
      env: "REFRESH_TOKEN_KEY"
